### ISSUE TITLE
Error while compiling coffer

### ISSUE THREAD

**Issue by ccgauche** [fee1-dead/coffer#1]
```
error[E0432]: unresolved import `syn::export`
  --> C:\Users\ccgauche\.cargo\registry\src\github.com-1ecc6299db9ec823\delegate-0.4.3\src\lib.rs:94:10
   |
94 | use syn::export::TokenStream2;
   |          ^^^^^^ could not find `export` in `syn`
```
The import used in Cargo.toml
`coffer = {git = "https://github.com/fee1-dead/coffer"}`
Toolchains tried:
 - Windows x86_64 - stable
 - Windows x86_64 - nightly
 - Linux x86_64 (WSL) - nightly
 - Linux x86_64 (WSL) - stable

I'm really happy to finally see a crate like this in Rust. I was searching for something like that for months.

**Comment by ccgauche** [comment]
After some testing the develop branch seems to work just fine but this is not the default branch so you should upgrade delegate to 0.5.1 on main branch

**Comment by fee1-dead** [comment]
Hi, I would suggest using 1.0.1, or git with branch = develop. GitLab is
used to host the code and GitHub is mirrored. I might use tags instead of
the current branching scheme.

**Comment by ccgauche** [comment]
Here the fix:
`coffer = {git="https://github.com/fee1-dead/coffer", branch = "develop"}`

**Comment by fee1-dead** [comment]
I just merged the `develop` branch into the main branch. That should resolve the issue. On a separate note, I am considering using branches and tags to track major releases, without the need to specify the branch in `Cargo.toml`.
